- name: Ansible Playbook to Install and Setup Apache on amazon linux
  hosts: all 
  tasks:
    - name: download the node exporter 
      get_url: 
        url: https://github.com/prometheus/node_exporter/releases/download/v1.6.0/node_exporter-1.6.0.linux-amd64.tar.gz
        dest: /opt/ 
